# Generated by Django 3.2.20 on 2023-08-06 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='location',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
