# Generated by Django 3.2.20 on 2023-08-06 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_usermodel_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='location',
        ),
        migrations.AddField(
            model_name='postjobmodel',
            name='location',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
